### ISSUE TITLE
How to set the value of "multfact" in HeatmapDataParameter?

### ISSUE THREAD

**Issue by fengyang0317** [tpfister/caffe-heatmap#1] opened 2015-11-06 03:33 UTC
The value is 0 by default. However, it is multiplied and divided by some some other value in data_heatmap.cpp, leading to nan error.

**Comment by xuxy09** [comment] 2015-11-07 23:45
Hi fengyang0317, are you still using this code? I'm having difficulty in using the heatmap-Caffe, and a lot of strange errors came up when I want to run the .sh file. Could you tell me the version of your CUDA? I want to know if that matters. Thx!

**Comment by tpfister** [comment] 2015-11-19 19:48
Hi Feng,
The default value of multfact should be 1 (it is a multiplication factor for the regression coordinates in your label file). This has been fixed in the latest commit.

**Comment by samouha** [comment] 2016-02-19 13:59
I'm having the same error please; and I couldn't find a solution. 
What I want to know is how to set the value of "multfact" please ?? because in the readme file, is said that "Note these files require multfact=282 in both training and testing data layers": mean that the images have to have mulfact=282 and @tpfister  you said that the dafault value is 1? 
Can you explain me that please ;

**Comment by fengyang0317** [comment] 2016-02-23 03:44
Hi,
If you are using Pfister's data, you should set multfact to 282. If you prepare data yourself, it should be 1.


Pfister's data is transformed using the value 282. 


I prefer to use fengyang0317@gmail.com.


Yang




At 2016-02-19 21:59:50, "Sameh Neili" <notifications@github.com> wrote:


I'm having the same error please; and I couldn't find a solution.
What I want to know is how to set the value of "multfact" please ?? because in the readme file, is said that "Note these files require multfact=282 in both training and testing data layers": mean that the images have to have mulfact=282 and @tpfister you said that the dafault value is 1?
Can you explain me that please ;

**Comment by samouha** [comment] 2016-02-23 09:40
Thanks @fengyang0317. So I have to add this variable "multfact" in the "train_val.prototxt" file , and set it to 282, isn't ?

**Comment by fengyang0317** [comment] 2016-02-23 13:53
yes，if you want to use his data.

在 2016-02-23 17:40:47，"Sameh Neili" <notifications@github.com> 写道：


Thanks @fengyang0317. So I have to add this variable "multfact" in the "train_val.prototxt" file , and set it to 282, isn't ?

**Comment by samouha** [comment] 2016-02-23 19:40
@xuxy09 did you finally succed to compile and run this code of caffeHeatmap? 
I still have many bugs and don"t know how to solve that , if you could post your errors and how did you solve them ? pearhaps that could help me and some others freinds as well :)

**Comment by tpfister** [comment] 2016-03-01 05:21
Multfact has been addressed in the latest commit

**Closed** 2016-03-01 05:22 UTC
